spring:
  application:
    name: weather-prediction-getter
  lifecycle:
    timeout-per-shutdown-phase: 15s # 15초 간의 우아한 종료 기간을 정의

server:
  port: 9002               # 서버가 연결을 받아들이는 포트
  shutdown: graceful       # 우아한 종료를 활성화
  netty:
    connection-timeout: 2s # 서버와 TCP 연결을 수립하기 위해 기다리는 시간
    idle-timeout: 15s      # 데이터가 전송되지 않는 경우 TCP 연결을 받기 전에 기다리는 시간

weather-open-api:
  service-key: 6uAMfC1RDTLntHVOUFCdZDwYeVhaIxKrKIw+iOVyFaHTp9Tfs/RTi8Ia4o1K+ScQ5fOZQFuqcxSD7dgRFinFNA==
  base-url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtFcst
  data-transfer-url: http://localhost:9090/weather/prediction
  num-of-rows: 1000
  page-no: 1
  data-type: JSON
  nx: 59
  ny: 126
